go.property("N", 6)

function init(self)
	msg.post(".", "acquire_input_focus")
	self.ids = {}
	-- the number of dice
	for i=1,self.N do
		local id = factory.create("/go#factory", vmath.vector3(100*i,200,0), nil, {dice_id = i})
		table.insert(self.ids,id)
	end
end

function on_input(self, action_id, action)
	if action_id == hash("touch") and action.pressed then
		for i=1,#self.ids do
			msg.post(self.ids[i],"roll")
		end
	end
end